### ISSUE TITLE
Potential API Query Parameter Discrepancy: `is_overdue` in Payables

### ISSUE THREAD

**Issue by radist2s** [team-monite/monite-sdk#295]
During the migration of the Monite repository to the [OpenAPI Qraft v2](https://openapi-qraft.github.io/openapi-qraft/docs/next/overview), I noticed a recent commit in `main` where Vitaliy added a filter for the `is_overdue` field in Payables. However, according to our OpenAPI documentation, the GET `/payables` endpoint does not support a `is_overdue` query parameter.

**Details:**
- **Commit Reference:** [The actual commit 🔗](https://github.com/team-monite/monite-sdk/commit/c8450cc8144dff0e89011d84d7aff60ea07fbea4#diff-015f6e47b413e81260ddf2ff82366727d3e8f229e87cf97ce862f92cfe9b160fR153) cc: @vkuprin
- **Endpoint:** GET `/payables`
- **Query Parameter:** `is_overdue`

**Possible Scenarios:**
1. The API has recently been updated to include this query parameter, but `schema.json` hasn't been updated.
2. The parameter doesn’t actually exist in the API, indicating a potential error in the implementation.

**Action Required:**
- Please verify whether the `is_overdue` query parameter is correctly implemented in the API.
- If it’s missing, please correct the implementation or update the OpenAPI documentation accordingly.

**Additional Note:**
There was an issue with the implementation of the `getQueryData(…)` function in Qraft, which has been fixed in the new version. This issue caused an incorrect type realization, which might be related.

**Comment by vkuprin** [comment]
Thank you for bringing this to attention.

Clarification:
The is_overdue filter is not currently supported by the GET /payables endpoint, as the implementation of filters is still in progress by the backend team. At this stage, only the overdue label tag is available, and full filter functionality, including is_overdue, will be added in a future update.

Next Steps:

	•	The backend team is aware and actively working on completing the filter implementation.
	•	We will update the OpenAPI documentation (schema.json) once these features are fully supported.

I appreciate the diligence in catching this, and we’re committed to aligning the implementation with the documentation. Please feel free to reach out if there are further questions or concerns

**Comment by vkuprin** [comment]
Thank you for highlighting this.

Clarification:
Currently, the is_overdue filter is not supported by the GET /payables endpoint, as the implementation of filters is still in progress by the backend team. At this stage, only the overdue label tag is available, and the full filter functionality, including is_overdue, will be added in a future update.

Impact:

	•	This issue is not critical and does not affect the app’s functionality. The main objective of adding the overdue label has been achieved, and no breaking changes have been introduced.

Next Steps:

•	The backend team is aware of this and is actively working to complete the filter implementation.
•	The OpenAPI documentation (schema.json) will be updated once these features are fully supported.

Thanks again for catching this. We’ll continue to ensure the implementation aligns with our documentation. Please let me know if there are any other questions or concerns.

**Comment by radist2s** [comment]
@vkuprin, thanks a lot for the clarification, will keep an eye out for updates.

**Comment by radist2s** [comment]
Yo, have you solved the issue with the `is_overdue` field if filter?

**Comment by vkuprin** [comment]
@radist2s  Yes, It's covered with custom filters that you can create and isOverdue was removed

For instance you can pass now from our customisation monite.ts

```ts
 MonitePayableTable: {
    defaultProps: {
      summaryCardFilters: {
        Unpaid: {
          status__in: ['draft', 'new', 'approve_in_progress', 'rejected'],
        },
        Scheduled: {
          tag_ids: ['f4031683-7605-48c6-969c-dcfc5397935b'],
          status__in: [
            'draft',
            'new',
            'approve_in_progress',
            'waiting_to_be_paid',
            'partially_paid',
          ],
        },
        Paid: {
          status__in: ['paid'],
        },
      /// you can put here logic for overdue based on what our payables query support as parametor and build even your own overdue logic
      },
    },


```
