### ISSUE TITLE
Monite drop-in throws "missing required prop `component`" error

### ISSUE THREAD

**Issue by akamittal** [team-monite/monite-sdk#66]
Greetings!

I was trying to embed drop-in to my project without providing `component` prop to the `<monite-app>`. It is throwing error -

![image](https://github.com/team-monite/monite-sdk/assets/17566644/47b1465a-f4a1-4ad3-86b3-b26867d0c0db)

But according to docs -

> The component attribute should only be used when you want to render specific pages from the Drop-in components library. Possible values for the component attribute include approval-policies, counterparts, onboarding, payables, products, receivables, and tags.

**Comment by radist2s** [comment]
@akamittal, thank you for reporting us. @chideraao, can I ask you to clarify our documentation? From it, there should be a change that for Drop In the `component` attribute is mandatory

**Comment by radist2s** [comment]
@akamittal, If you mean the ability to display [a side menu](https://github.com/team-monite/monite-sdk/assets/725645/a26a71dc-2eef-45f8-af38-3e32cfa9560f) you'll probably have to create it yourself, as Drop In does not provide it.

**Comment by akamittal** [comment]
Alright. I have one more question. If drop-in renders single component at a time then what's the difference between drop-in and react-sdk? Because both are doing the same thing in a slightly different way.

**Comment by chideraao** [comment]
@akamittal The React SDK is ideal for React-based applications. The Drop-in library on the other hand is language-agnostic and can be used directly in HTML or across any JavaScript framework.

**Comment by akamittal** [comment]
Thanks. Closing the issue.
